const CONSTANTS = {
  BLANKSPACE: ' ',
  BLANK: '',
  INDEX: 'index',
  HASHTAG: '#',
  TABCHANGE: 'tsc:tab-change',
  DARK: 'dark',
  LIGHT: 'light',
  THEME: 'theme',
  PREFERSCHEME: '(prefers-color-scheme: dark)',
  SUCCESS: 'success',
  ERROR: 'error',
  TRUE: 'true',
  FALSE: 'false',
  CLASS: 'class',
  HIDDEN: 'hidden',
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  VISIBLECLASS: 'visibleClass',
  INVISIBLECLASS: 'invisibleClass',
  ACTIVECLASS: 'activeClass',
  ENTERINGCLASS: 'enteringClass',
  ENTERTIMEOUT: 'enterTimeout',
  LEAVINGCLASS: 'leavingClass',
  LEAVINGTIMEOUT: 'leaveTimeout',
  ACTIVETAB: 'activeTab',
  INACTIVETAB: 'inactiveTab',
  ACTIVETABICON: 'activeTabIcon',
  INACTIVETABICON: 'inactiveTabIcon',
  DARKMODE: 'darkMode',
  ON: 'on',
  ACTIVETARGET: 'activeTarget',
  ERRORREADING: 'Error Reading File',
  GENERATORS: 'generators',
  ERRORREADING: 'Error Reading File',
  DOCUMENT: 'document',
  UTF8: 'UTF-8',
  RETURNNEWLINE: '\r\n',
  DASH: '-',
  TEMPLATE: '-template',
  TOGGLE: '-toggle',
  OUTPUTFORM: 'output-form',
  DOWNLOADBTN: 'download-btn',
  CURLYBRAKETSTART: '{',
  CURLYBRAKETEND: '}',
  COMMASPACE: ', ',
  DOUBLEQUOTE: '"',
  QUOTECOLON: '": ',
  QUOTECOLONQUOTE: '": "',
  NEWLINE: '\n',
  BRACKETSTART: '[',
  BRACKETEND: ']',
  COPY: {
    CMD: 'copy',
    INPUT: 'textarea',
    NOTIFICATION: 'copy-notification',
    BUTTON: 'copy-btn',
  },
  TARGETS: {
    MENU: 'menu',
    OVERLAY: 'overlay',
    SIDEBAR: 'sidebar',
    TOGGLE: 'toggle',
    ONICON: 'onIcon',
    OFFICON: 'offIcon',
    TAB: 'tab',
    PANEL: 'panel',
    CONTENT: 'content',
    CONTAINER: 'container',
    BACKGROUND: 'background',
    VIEW: 'view',
  },
  CLASSES: {
    HIDE: 'hide',
    OVERLAYENTER: 'overlayEntering',
    OVERLAYLEAVE: 'overlayLeaving',
    SIDEBARENTER: 'sidebarEntering',
    SIDEBARLEAVE: 'sidebarLeaving',
    ENTERING: 'entering',
    LEAVING: 'leaving',
    TOBACKGROUND: 'toBackground',
    FROMBACKGROUND: 'fromBackground',
    ONBACKGROUND: 'onBackground',
    OFFBACKGROUND: 'offBackground',
    TOVIEW: 'toView',
    FROMVIEW: 'fromView',
    ONICON: 'onIcon',
    OFFICON: 'offIcon',
    ONTOGGLE: 'onToggle',
    OFFTOGGLE: 'offToggle',
  },
  DOM: {
    HTML: 'html',
    SVG: 'svg',
  },
  DATATYPES: {
    TEXT: 'text',
    CHECKBOX: 'checkbox',
    SIMPLEARRAY: 'simpleArray',
    MULTICOLUMN: 'multipleColumn',
    COMPLEXTABLE: 'complexTable',
    COMPLEXARRAY: 'complexArray',
  },
  TEXT: {
    WHITE: 'text-white',
    GRAY800: 'text-gray-800',
    DARK: {
      GRAY100: 'dark:text-gray-100',
    },
    HOVER: {
      WHITE: 'hover:text-white',
    },
    GROUPHOVER: {
      GRAY50: 'group-hover:text-gray-50',
    },
  },
  BG: {
    PURPLE700: 'bg-purple-700',
    GRAY200: 'bg-gray-200',
    HOVER: {
      PURPLE500: 'hover:bg-purple-500',
    },
  },
  OPACITY: {
    O100: 'opacity-100',
    O0: 'opacity-0',
  },
  TRANSLATE: {
    X0: 'translate-x-0',
    X5: 'translate-x-5',
    X7: 'translate-x-7',
    XFULL: 'translate-x-full',
    Y0: 'translate-y-0',
    Y4: 'translate-y-4',
    SM: {
      Y0: 'translate-y-0',
    },
  },
  EASE: {
    IN: 'ease-in',
    OUT: 'ease-out',
  },
  DURATION: {
    D100: 'duration-100',
    D200: 'duration-200',
    D300: 'duration-300',
  },
  SCALE: {
    SM: {
      S100: 'sm:scale-100',
      S95: 'sm:scale-95',
    },
  },
  POSITION: {
    FIXED: 'fixed',
  },
  OVERFLOW: {
    HIDDEN: 'overflow-hidden',
  },
  INSET: {
    X0: 'inset-x-0',
  },
};

export {CONSTANTS};
